'use client';
import {useState} from 'react';
import {enumLabel,rankLabel,targetKey,visibleTargets} from '../../lib/recruiting.mjs';
type Enum={value:number;label:string};
type Target={record_id:{table_id:number;row_id:number};name:string;position:Enum;national_rank:number;position_rank:number;stage:Enum;scholarship:Enum;hours_spent_current:number};
type Board={hours_total:number;hours_assigned:number;hours_processed:number;targets:Target[]};
export default function RecruitingView({board,team}:{board:Board|null;team:string}){
 const [query,setQuery]=useState(''),[position,setPosition]=useState('All'),[stage,setStage]=useState('All'),[sort,setSort]=useState('rank');
 if(!board)return <><h1>Recruiting</h1><section className="card"><h2>Recruiting board unavailable</h2><p>This snapshot does not include a recruiting board. This does not mean you have zero targets or hours.</p></section></>;
 const positions=Array.from(new Set(board.targets.map(t=>enumLabel(t.position)))).sort(),stages=Array.from(new Set(board.targets.map(t=>enumLabel(t.stage)))).sort();
 const visible=visibleTargets(board.targets,query,position,stage,sort);
 return <><h1>Recruiting</h1><p>{team} · {board.targets.length} targets</p><div className="grid section-stats">{[['Total hours',board.hours_total],['Assigned hours',board.hours_assigned],['Processed hours',board.hours_processed],['Board targets',board.targets.length]].map(([label,value])=><section className="card" key={label}><p>{label}</p><strong className="stat">{value??'—'}</strong></section>)}</div><p className="note">Hours reflect this saved board, not a live balance. Target hours are shown separately.</p>
 <label className="sr-only" htmlFor="recruit-search">Search recruits by name</label><input id="recruit-search" className="roster-search" type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search recruits…"/>
 <div className="roster-controls"><label>Position<select value={position} onChange={e=>setPosition(e.target.value)}><option value="All">All positions</option>{positions.map(p=><option key={p}>{p}</option>)}</select></label><label>Stage<select value={stage} onChange={e=>setStage(e.target.value)}><option value="All">All stages</option>{stages.map(s=><option key={s}>{s}</option>)}</select></label><label>Sort by<select value={sort} onChange={e=>setSort(e.target.value)}><option value="rank">National rank</option><option value="hours">Current hours: high to low</option><option value="name">Name: A–Z</option></select></label></div>
 <p className="result-count" role="status">Showing {visible.length} of {board.targets.length} targets</p>
 {visible.length===0?<section className="card"><h2>{board.targets.length===0?'No recruiting targets':'No matching recruits'}</h2><p>{board.targets.length===0?'This saved board is empty.':'Try another name, position, or stage.'}</p>{board.targets.length>0&&<button className="back" onClick={()=>{setQuery('');setPosition('All');setStage('All');}}>Clear filters</button>}</section>:visible.map((target:Target)=><details className="card recruit-card" key={targetKey(target)}><summary><span><strong className="player-name">{target.name}</strong><small>{enumLabel(target.position)} · National rank {rankLabel(target.national_rank)}</small><span className="recruit-stage">{enumLabel(target.stage)}</span></span><span className="recruit-hours"><strong>{target.hours_spent_current??'—'}</strong><small>hours</small><small>Details ⌄</small></span></summary><dl><dt>Position rank</dt><dd>{rankLabel(target.position_rank)}</dd><dt>Recruiting stage</dt><dd>{enumLabel(target.stage)}</dd><dt>Scholarship status</dt><dd>{enumLabel(target.scholarship)}</dd><dt>Current target hours</dt><dd>{target.hours_spent_current??'Unavailable'}</dd></dl></details>)}
 <p className="note">Tap a recruit to expand details. Rankings and statuses come from the snapshot; commitment odds and star ratings are not available.</p></>;
}
